# Generated by Django 4.2.4 on 2023-08-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_room_room_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.IntegerField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400')], max_length=20),
        ),
    ]
